version: '3.8'

services:
  auth-db:
    image: mongo:latest
    container_name: breezy-auth-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  post-db:
    image: postgres:latest
    container_name: breezy-post-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: breezy_posts
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mongo_data:
  postgres_data: